name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2
    - name: Silent git warning by configuring pull strategy
      run: git config --global pull.ff only
    - name: Download submodules
      run: ./buildutils/clone-submodules.sh
    - name: Update submodules
      run: ./buildutils/update-submodules.sh
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Extract signing keystore
      run: echo "${{ secrets.SIGNING_KEY }}" | base64 -d > ~/abm.keystore
    - name: Set signing configuration
      run: mkdir -p ~/.gradle && echo "${{ secrets.KEY_SETTINGS }}" | base64 -d > ~/.gradle/gradle.properties
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload apks (1/2)
      uses: actions/upload-artifact@v2
      with:
        name: other_apks
        path: app/build/outputs/apk/*/*.apk
    - name: Upload apks (2/2)
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
